### ISSUE TITLE
Make content inside of target be clickable [Counter-intuitive]

### ISSUE THREAD

**Issue by JamMaster1999** [sjmc11/tourguide-js#34]
Is there a way to make the content inside the target clickable? Right now the opposite is true. The content outside of the target is clickable and the content inside is not clickable. 
This is counter intuitive to the user because they should be able to easily click inside the target so that they can practice using the product through the interactive tutorial. 

Besides that great library!!

**Comment by ra-dave** [comment]
I have the same question.  I need the user to be able to interact with my input field while the tour is in progress.

**Comment by ptrtht** [comment]
Same here! Would like my user to click things / enter text into target element.

Without these the package, although very nice is not really functional :(

**Comment by faoiseamh** [comment]
I'll add my vote for this as well. Just stumbled across this library and it looks fantastic all around, but without the ability to interact with targeted elements, this wouldn't be usable for most use cases I'd otherwise love to adopt it for.

From working through issues with the implementation of interactive-highlighted elements with similar libraries, I can appreciate the challenges involved in achieving this robustly across a diversity of contexts and browsers, so I know this isn't exactly a light lift, but are there any plans or thoughts maintainers / contributors could share on this front?

Appreciate the work regardless, this is a great little package!

**Comment by sjmc11** [comment]
Hey, thanks for the conversation on this issue.

Definitely something that can be made possible with a configuration option. I'll try and find the time to get this updated soon. 

Will likely be early September due to other commitments.

**Comment by JamMaster1999** [comment]
Hey guys, sorry I forgot to update everyone here. 
You can very simply fix this by: 
`document.querySelector(".tg-backdrop").style.pointerEvents = "none"`

**Comment by sjmc11** [comment]
The solution to this has been merged and released on npm as version [0.0.18](https://www.npmjs.com/package/@sjmc11/tourguidejs)

You can now use the `propagateEvents` option on steps.

Thanks to @Akxe for getting round to it.

**Comment by kathleen-ju** [comment]
@sjmc11 does the `propagateEvents` only works if `exitOnClickOutside` is set to false? It seems like the case for me... 
Is there a way to set `exitOnClickOutside` but user can still click on the element inside target highlighted area? Setting `tg-backdrop").style.pointerEvents = "none"` doesnt fix it...
